package UI;

import businessLogic.BookStore;
import businessLogic.ExceptionManager;
import data.Admin;
import data.Book;
import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class AddBookWindow extends javax.swing.JFrame {

    private String coverFilePath;
    private static String review;

    public AddBookWindow() {
        initComponents();

        clearFields();

        setTitle("\ud83d\udcda Bookotá");
        setIconImage(new ImageIcon(getClass().getResource("/Imagen/Bookota.png"))
                .getImage());// Icono de la ventana

        setLocationRelativeTo(null);

        ImageIcon imagen1 = new ImageIcon(getClass().getResource("/Imagen/AddBooks.png"));
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(jLabelAddBooksIcon.getWidth(), jLabelAddBooksIcon.getHeight(), Image.SCALE_SMOOTH));
        jLabelAddBooksIcon.setIcon(fondo1);
        this.repaint();
    }

    private void clearFields() {
        coverFilePath = "/Imagen/EmptyBookCover.png";
        review = "";
        txtAuthor.setText("");
        txtCoverType.setText("");
        txtEditorial.setText("");
        txtISBNCode.setText("");
        txtNumberOfPages.setText("");
        txtPrice.setText("");
        txtStock.setText("");
        txtTitle.setText("");
        cbxGenres.setSelectedIndex(0);
    }

    public static String getReview() {
        return review;
    }

    public static void setReview(String review) {
        AddBookWindow.review = review;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAddBooksBackground = new javax.swing.JPanel();
        jLabelAddBooks = new javax.swing.JLabel();
        jLabelAddBooksIcon = new javax.swing.JLabel();
        jLabelISBN = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelNumberPages = new javax.swing.JLabel();
        jLabelAuthor = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtISBNCode = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        jLabelCover = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelEditorial = new javax.swing.JLabel();
        jLabelQuantity = new javax.swing.JLabel();
        txtCoverType = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btnAddBook = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEditorial = new javax.swing.JTextField();
        txtNumberOfPages = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnChooseCover = new javax.swing.JButton();
        btnWriteReview = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        cbxGenres = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelAddBooksBackground.setBackground(new java.awt.Color(40, 47, 93));

        jLabelAddBooks.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAddBooks.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAddBooks.setText("Creación de libros");

        jLabelISBN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelISBN.setForeground(new java.awt.Color(255, 255, 255));
        jLabelISBN.setText("Código ISBN");

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Título");

        jLabelGender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelGender.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGender.setText("Género");

        jLabelNumberPages.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNumberPages.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumberPages.setText("Número de páginas");

        jLabelAuthor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelAuthor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAuthor.setText("Autor");

        jLabelCover.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCover.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCover.setText("Empastado");

        jLabelPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPrice.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrice.setText("Precio");

        jLabelEditorial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelEditorial.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEditorial.setText("Editorial");

        jLabelQuantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelQuantity.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQuantity.setText("Stock");

        btnAddBook.setText("Agregar Libro");
        btnAddBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddBookMouseEntered(evt);
            }
        });
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("© Todos los derechos reservados. 2019.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        btnChooseCover.setText("Escoger portada");
        btnChooseCover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChooseCoverMouseEntered(evt);
            }
        });
        btnChooseCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseCoverActionPerformed(evt);
            }
        });

        btnWriteReview.setText("Escribir sinopsis");
        btnWriteReview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnWriteReviewMouseEntered(evt);
            }
        });
        btnWriteReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteReviewActionPerformed(evt);
            }
        });

        btnReturn.setText("Volver");
        btnReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReturnMouseEntered(evt);
            }
        });
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        cbxGenres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Literatura Universal", "Literatura Juvenil", "Fantasía", "Romance", "Terror", "Novela" }));
        cbxGenres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGenresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddBooksBackgroundLayout = new javax.swing.GroupLayout(jPanelAddBooksBackground);
        jPanelAddBooksBackground.setLayout(jPanelAddBooksBackgroundLayout);
        jPanelAddBooksBackgroundLayout.setHorizontalGroup(
            jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelAddBooksBackgroundLayout.createSequentialGroup()
                .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddBooksBackgroundLayout.createSequentialGroup()
                        .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAddBooksBackgroundLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelAddBooksBackgroundLayout.createSequentialGroup()
                                        .addGap(154, 154, 154)
                                        .addComponent(jLabelAddBooks))
                                    .addGroup(jPanelAddBooksBackgroundLayout.createSequentialGroup()
                                        .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cbxGenres, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                            .addComponent(jLabelAuthor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelISBN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                            .addComponent(txtTitle, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtISBNCode)
                                            .addComponent(txtAuthor, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabelAddBooksIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelAddBooksBackgroundLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelEditorial)
                                .addComponent(txtCoverType)
                                .addComponent(jLabelCover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelNumberPages, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addComponent(txtEditorial)
                                .addComponent(txtNumberOfPages)
                                .addComponent(txtPrice))
                            .addGroup(jPanelAddBooksBackgroundLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnWriteReview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnChooseCover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanelAddBooksBackgroundLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanelAddBooksBackgroundLayout.setVerticalGroup(
            jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddBooksBackgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelAddBooks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelISBN)
                        .addComponent(jLabelCover))
                    .addComponent(jLabelAddBooksIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtISBNCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCoverType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle)
                    .addComponent(jLabelPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGender)
                    .addComponent(jLabelEditorial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxGenres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAuthor)
                    .addComponent(jLabelNumberPages))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumberOfPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuantity)
                    .addComponent(btnChooseCover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnWriteReview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanelAddBooksBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBook)
                    .addComponent(btnReturn))
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAddBooksBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAddBooksBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        int numberOfPages, stock, price, index;
        String isbnCode, title, genre, author, typeOfCover, editorial;
        if (ExceptionManager.checkIntegerValue(txtPrice) || ExceptionManager.checkIntegerValue(txtNumberOfPages)
                || ExceptionManager.checkIntegerValue(txtStock)) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese correctamente los datos",
                    "", JOptionPane.ERROR_MESSAGE);
        } else {
            index = BookStore.getLastBookIndex() + 1;
            isbnCode = txtISBNCode.getText();
            title = txtTitle.getText();
            genre = cbxGenres.getSelectedItem().toString();
            author = txtAuthor.getText();
            typeOfCover = txtCoverType.getText();
            editorial = txtEditorial.getText();
            numberOfPages = Integer.parseInt(txtNumberOfPages.getText());
            stock = Integer.parseInt(txtStock.getText());
            price = Integer.parseInt(txtPrice.getText());
            if (isbnCode.length() == 0 || title.length() == 0 || genre.length() == 0
                    || author.length() == 0 || typeOfCover.length() == 0 || editorial.length() == 0
                    || numberOfPages == 0 || stock == 0 || price == 0 || review.length() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Por favor llene todos los campos",
                        "", JOptionPane.ERROR_MESSAGE);
            } else {
                int answer = JOptionPane.showConfirmDialog(rootPane, "Está de seguro?", "", JOptionPane.YES_NO_OPTION);
                if (answer == 0) {
                    Book newBook = BookStore.getAdmin().createNewBook(index, numberOfPages, stock, price, isbnCode, title, genre, author, typeOfCover, editorial, coverFilePath, review);
                    Admin.addNewBook(newBook);
                    JOptionPane.showMessageDialog(rootPane, "Libro creado con éxito", "", JOptionPane.INFORMATION_MESSAGE);
                    clearFields();
                }
            }
        }
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnChooseCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseCoverActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG, JPG, JPEG", "png", "jpg", "jpeg");
        fileChooser.setFileFilter(filter);
        int selection = fileChooser.showOpenDialog(rootPane);
        if (selection == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            coverFilePath = "/Imagen/Portadas/" + file.getName();
        }
    }//GEN-LAST:event_btnChooseCoverActionPerformed

    private void btnWriteReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteReviewActionPerformed
        WriteReviewWindow writeReviewWindow = new WriteReviewWindow();
        writeReviewWindow.setVisible(true);

    }//GEN-LAST:event_btnWriteReviewActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        setVisible(false);
        AdminWindow adminWindow = new AdminWindow();
        adminWindow.setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        BookStore.close(rootPane);
    }//GEN-LAST:event_formWindowClosing

    private void cbxGenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGenresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxGenresActionPerformed

    private void btnChooseCoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChooseCoverMouseEntered
        btnChooseCover.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnChooseCoverMouseEntered

    private void btnWriteReviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWriteReviewMouseEntered
        btnWriteReview.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnWriteReviewMouseEntered

    private void btnReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseEntered
        btnReturn.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnReturnMouseEntered

    private void btnAddBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBookMouseEntered
        btnAddBook.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnAddBookMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBookWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBookWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBookWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBookWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBookWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnChooseCover;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnWriteReview;
    private javax.swing.JComboBox<String> cbxGenres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAddBooks;
    private javax.swing.JLabel jLabelAddBooksIcon;
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelCover;
    private javax.swing.JLabel jLabelEditorial;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelNumberPages;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAddBooksBackground;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtCoverType;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtISBNCode;
    private javax.swing.JTextField txtNumberOfPages;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
