package UI;

import businessLogic.BookStore;
import data.Book;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Image;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.MutableAttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

public class BookViewWindow extends javax.swing.JFrame {

    private static Book book;

    public BookViewWindow() throws IOException {
        initComponents();

        setTitle("\ud83d\udcda Bookotá");
        setIconImage(new ImageIcon(getClass().getResource("/Imagen/Bookota.png")).getImage());
        setLocationRelativeTo(null);

        ImageIcon imagen1 = new ImageIcon(book.getCoverFilePath());
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(jLabelBookCoverPage.getWidth(), jLabelBookCoverPage.getHeight(), Image.SCALE_SMOOTH));
        jLabelBookCoverPage.setIcon(fondo1);
        this.repaint();

        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/Imagen/Wish1.png"));
        Icon fondo2 = new ImageIcon(imagen2.getImage().getScaledInstance(jButtonAddToWishList.getWidth(), jButtonAddToWishList.getHeight(), Image.SCALE_SMOOTH));
        jButtonAddToWishList.setIcon(fondo2);
        this.repaint();

        ImageIcon imagen3 = new ImageIcon(getClass().getResource("/Imagen/ShoppingCart1.png"));
        Icon fondo3 = new ImageIcon(imagen3.getImage().getScaledInstance(jButtonBuyBook.getWidth(), jButtonBuyBook.getHeight(), Image.SCALE_SMOOTH));
        jButtonBuyBook.setIcon(fondo3);
        this.repaint();

        ImageIcon imagen4 = new ImageIcon(getClass().getResource("/Imagen/Home1.png"));
        Icon fondo4 = new ImageIcon(imagen4.getImage().getScaledInstance(btnHome.getWidth(), btnHome.getHeight(), Image.SCALE_SMOOTH));
        btnHome.setIcon(fondo4);
        this.repaint();

        ImageIcon imagen5 = new ImageIcon(getClass().getResource("/Imagen/Facebook.png"));
        Icon fondo5 = new ImageIcon(imagen5.getImage().getScaledInstance(jLabelFacebookIcon2.getWidth(), jLabelFacebookIcon2.getHeight(), Image.SCALE_SMOOTH));
        jLabelFacebookIcon2.setIcon(fondo5);
        this.repaint();

        ImageIcon imagen6 = new ImageIcon(getClass().getResource("/Imagen/Instagram.png"));
        Icon fondo6 = new ImageIcon(imagen6.getImage().getScaledInstance(jLabelInstagramIcon2.getWidth(), jLabelInstagramIcon2.getHeight(), Image.SCALE_SMOOTH));
        jLabelInstagramIcon2.setIcon(fondo6);
        this.repaint();

        ImageIcon imagen7 = new ImageIcon(getClass().getResource("/Imagen/Twitter.png"));
        Icon fondo7 = new ImageIcon(imagen7.getImage().getScaledInstance(jLabelTwitterIcon2.getWidth(), jLabelTwitterIcon2.getHeight(), Image.SCALE_SMOOTH));
        jLabelTwitterIcon2.setIcon(fondo7);
        this.repaint();

        StyledDocument doc = txtpaneSynopsis.getStyledDocument();
        MutableAttributeSet justify = new SimpleAttributeSet();
        StyleConstants.setAlignment(justify, StyleConstants.ALIGN_JUSTIFIED);
        StyleConstants.setLineSpacing(justify, 0.6f);
        doc.setParagraphAttributes(0, doc.getLength(), justify, false);

        setBookInfo();
    }

    private void setBookInfo() {
        jlabelBookTitle.setText(book.getTitle());
        jlabelBookEditorial.setText(book.getEditorial());
        jlabelBookAuthor.setText(book.getAuthor());
        jlabelBookPrice.setText("$" + book.getPrice());
        jlabelBookStock.setText(Integer.toString(book.getStock()));
        jlabelBookISBNCode.setText(book.getIsbnCode());
        jlabelBookGenre.setText(book.getGenre());
        jlabelBookCover.setText(book.getTypeOfCover());
        jlabelBookPages.setText(Integer.toString(book.getNumberOfPages()));
        txtpaneSynopsis.setText(book.getReview());

        ImageIcon cover = new ImageIcon(getClass().getResource(book.getCoverFilePath()));
        Icon coverBackground = new ImageIcon(cover.getImage().getScaledInstance(jLabelBookCoverPage.getWidth(), jLabelBookCoverPage.getHeight(), Image.SCALE_SMOOTH));
        jLabelBookCoverPage.setIcon(coverBackground);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelBookota = new javax.swing.JPanel();
        jPanelFreeShipping = new javax.swing.JPanel();
        jLabelFreeShipping = new javax.swing.JLabel();
        jLabelAppLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneSearch = new javax.swing.JTextPane();
        jLabelMiAccount = new javax.swing.JLabel();
        jLabelHomeIcon = new javax.swing.JLabel();
        jPanelShoppingCart = new javax.swing.JPanel();
        jLabelShoppingCart = new javax.swing.JLabel();
        jLabelShoppingC = new javax.swing.JLabel();
        jPanelWishList = new javax.swing.JPanel();
        jLabelWishList = new javax.swing.JLabel();
        jLabelWishListIcon = new javax.swing.JLabel();
        jLabelCategories = new javax.swing.JLabel();
        jPanelYoungAdultLiterature = new javax.swing.JPanel();
        jLabelYoungAdultLiterature = new javax.swing.JLabel();
        jPanelUniversal = new javax.swing.JPanel();
        jLabelUniversal = new javax.swing.JLabel();
        jPanelFantasy = new javax.swing.JPanel();
        jLabelFantasy = new javax.swing.JLabel();
        jPanelRomance = new javax.swing.JPanel();
        jLabelRomance = new javax.swing.JLabel();
        jPanelCrime = new javax.swing.JPanel();
        jLabelCrime = new javax.swing.JLabel();
        jPanelNovels = new javax.swing.JPanel();
        jLabelNovels = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabelSomeAvailableBooks = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jLabelPaula = new javax.swing.JLabel();
        jLabelRomeoYJulieta = new javax.swing.JLabel();
        jLabelJaneEyre = new javax.swing.JLabel();
        jLabelElExtranjeroPrice = new javax.swing.JLabel();
        jLabelPaulaPrice = new javax.swing.JLabel();
        jLabelRomeoYJulietaPrice = new javax.swing.JLabel();
        jLabelJaneEyrePrice = new javax.swing.JLabel();
        jPanelRightsReserved = new javax.swing.JPanel();
        jLabelRightsReserved = new javax.swing.JLabel();
        jLabelFacebookIcon = new javax.swing.JLabel();
        jLabelInstagramIcon = new javax.swing.JLabel();
        jLabelTwitterIconB = new javax.swing.JLabel();
        jLabelIfIStayAuthor = new javax.swing.JLabel();
        jLabelElExtranjeroAuthor = new javax.swing.JLabel();
        jLabelPaulaAuthor = new javax.swing.JLabel();
        jLabelRomeoYJulietaAuthor = new javax.swing.JLabel();
        jLabelJaneEyreAuthor = new javax.swing.JLabel();
        jPanelMonthlyFindings = new javax.swing.JPanel();
        jLabelFindings = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jLabelFindingsPeerOfBooks = new javax.swing.JLabel();
        jLabelElExtranjero = new javax.swing.JLabel();
        jLabelIfIStay = new javax.swing.JLabel();
        jLabelElExtranjeroPrice1 = new javax.swing.JLabel();
        jLabelMenuIcon = new javax.swing.JLabel();
        jLabelPayment = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneSearch1 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelHeaderPurple = new javax.swing.JPanel();
        jPanelHeaderFreeShipping = new javax.swing.JPanel();
        jLabelFreeShipping1 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        jLabelAppLogo1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelInstagramIcon2 = new javax.swing.JLabel();
        jLabelTwitterIcon2 = new javax.swing.JLabel();
        jLabelFacebookIcon2 = new javax.swing.JLabel();
        jlabelBookTitle = new javax.swing.JLabel();
        jlabelEditorial = new javax.swing.JLabel();
        jlabelAuthor = new javax.swing.JLabel();
        jLabelDataSheet = new javax.swing.JLabel();
        jLabelAddToWishList = new javax.swing.JLabel();
        jLabelPurchasing = new javax.swing.JLabel();
        jlabelGenre = new javax.swing.JLabel();
        jlabelBookGenre = new javax.swing.JLabel();
        jlabelBookEditorial = new javax.swing.JLabel();
        jlabelBookAuthor = new javax.swing.JLabel();
        jlabelCover = new javax.swing.JLabel();
        jlabelBookCover = new javax.swing.JLabel();
        jLabelBookCoverPage = new javax.swing.JLabel();
        jlabelPrice = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlabelBookPrice = new javax.swing.JLabel();
        jlabelISBNCode = new javax.swing.JLabel();
        jlabelBookISBNCode = new javax.swing.JLabel();
        jlabelPages = new javax.swing.JLabel();
        jlabelBookPages = new javax.swing.JLabel();
        jlabelStock = new javax.swing.JLabel();
        jlabelBookStock = new javax.swing.JLabel();
        jButtonShoppingCart = new javax.swing.JButton();
        jlabelBookTitle1 = new javax.swing.JLabel();
        jButtonAddToWishList = new javax.swing.JButton();
        jButtonBuyBook = new javax.swing.JButton();
        jButtonMyWishes = new javax.swing.JButton();
        jLabelAppLogo2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtpaneSynopsis = new javax.swing.JTextPane();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        jPanelBookota.setBackground(new java.awt.Color(40, 47, 93));
        jPanelBookota.setAlignmentX(0.0F);
        jPanelBookota.setAlignmentY(0.0F);

        jPanelFreeShipping.setBackground(new java.awt.Color(255, 153, 51));

        jLabelFreeShipping.setBackground(new java.awt.Color(255, 37, 69));
        jLabelFreeShipping.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFreeShipping.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFreeShipping.setText("Envíos gratis en Bogotá. Pedidos con duración máxima de envío de 24 horas.");
        jLabelFreeShipping.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanelFreeShippingLayout = new javax.swing.GroupLayout(jPanelFreeShipping);
        jPanelFreeShipping.setLayout(jPanelFreeShippingLayout);
        jPanelFreeShippingLayout.setHorizontalGroup(
            jPanelFreeShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFreeShippingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFreeShipping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFreeShippingLayout.setVerticalGroup(
            jPanelFreeShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFreeShippingLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabelFreeShipping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jTextPaneSearch);

        jLabelMiAccount.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMiAccount.setText("Mi cuenta");

        jLabelHomeIcon.setAlignmentX(0.5F);
        jLabelHomeIcon.setMaximumSize(new java.awt.Dimension(15, 15));

        javax.swing.GroupLayout jPanelBookotaLayout = new javax.swing.GroupLayout(jPanelBookota);
        jPanelBookota.setLayout(jPanelBookotaLayout);
        jPanelBookotaLayout.setHorizontalGroup(
            jPanelBookotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFreeShipping, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelBookotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAppLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMiAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelHomeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBookotaLayout.setVerticalGroup(
            jPanelBookotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBookotaLayout.createSequentialGroup()
                .addGroup(jPanelBookotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBookotaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelBookotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMiAccount)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAppLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelFreeShipping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelBookotaLayout.createSequentialGroup()
                        .addComponent(jLabelHomeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelShoppingCart.setBackground(new java.awt.Color(0, 153, 153));

        jLabelShoppingCart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelShoppingCart.setText("Mis compras");

        javax.swing.GroupLayout jPanelShoppingCartLayout = new javax.swing.GroupLayout(jPanelShoppingCart);
        jPanelShoppingCart.setLayout(jPanelShoppingCartLayout);
        jPanelShoppingCartLayout.setHorizontalGroup(
            jPanelShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShoppingCartLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jLabelShoppingC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelShoppingCart)
                .addGap(140, 140, 140))
        );
        jPanelShoppingCartLayout.setVerticalGroup(
            jPanelShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelShoppingC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelShoppingCartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelShoppingCart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelWishList.setBackground(new java.awt.Color(0, 153, 153));

        jLabelWishList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelWishList.setText("Mi lista de deseos");

        javax.swing.GroupLayout jPanelWishListLayout = new javax.swing.GroupLayout(jPanelWishList);
        jPanelWishList.setLayout(jPanelWishListLayout);
        jPanelWishListLayout.setHorizontalGroup(
            jPanelWishListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWishListLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jLabelWishListIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelWishList)
                .addGap(119, 119, 119))
        );
        jPanelWishListLayout.setVerticalGroup(
            jPanelWishListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWishListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWishList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabelWishListIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelCategories.setText("CATEGORÍAS");

        jPanelYoungAdultLiterature.setBackground(new java.awt.Color(40, 47, 93));

        jLabelYoungAdultLiterature.setForeground(new java.awt.Color(255, 255, 255));
        jLabelYoungAdultLiterature.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelYoungAdultLiterature.setText("Literatura Juvenil");

        javax.swing.GroupLayout jPanelYoungAdultLiteratureLayout = new javax.swing.GroupLayout(jPanelYoungAdultLiterature);
        jPanelYoungAdultLiterature.setLayout(jPanelYoungAdultLiteratureLayout);
        jPanelYoungAdultLiteratureLayout.setHorizontalGroup(
            jPanelYoungAdultLiteratureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelYoungAdultLiteratureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelYoungAdultLiterature, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelYoungAdultLiteratureLayout.setVerticalGroup(
            jPanelYoungAdultLiteratureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelYoungAdultLiterature, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jPanelUniversal.setBackground(new java.awt.Color(40, 47, 93));

        jLabelUniversal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUniversal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUniversal.setText("Literatura Universal");

        javax.swing.GroupLayout jPanelUniversalLayout = new javax.swing.GroupLayout(jPanelUniversal);
        jPanelUniversal.setLayout(jPanelUniversalLayout);
        jPanelUniversalLayout.setHorizontalGroup(
            jPanelUniversalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUniversalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUniversal, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelUniversalLayout.setVerticalGroup(
            jPanelUniversalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelUniversal, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jPanelFantasy.setBackground(new java.awt.Color(40, 47, 93));

        jLabelFantasy.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFantasy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFantasy.setText("Fantasía");

        javax.swing.GroupLayout jPanelFantasyLayout = new javax.swing.GroupLayout(jPanelFantasy);
        jPanelFantasy.setLayout(jPanelFantasyLayout);
        jPanelFantasyLayout.setHorizontalGroup(
            jPanelFantasyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFantasyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFantasy, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFantasyLayout.setVerticalGroup(
            jPanelFantasyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelFantasy, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jPanelRomance.setBackground(new java.awt.Color(40, 47, 93));

        jLabelRomance.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRomance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRomance.setText("Romance");

        javax.swing.GroupLayout jPanelRomanceLayout = new javax.swing.GroupLayout(jPanelRomance);
        jPanelRomance.setLayout(jPanelRomanceLayout);
        jPanelRomanceLayout.setHorizontalGroup(
            jPanelRomanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRomanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRomance, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRomanceLayout.setVerticalGroup(
            jPanelRomanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelRomance, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jPanelCrime.setBackground(new java.awt.Color(40, 47, 93));

        jLabelCrime.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCrime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCrime.setText("Crimen");

        javax.swing.GroupLayout jPanelCrimeLayout = new javax.swing.GroupLayout(jPanelCrime);
        jPanelCrime.setLayout(jPanelCrimeLayout);
        jPanelCrimeLayout.setHorizontalGroup(
            jPanelCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCrime, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCrimeLayout.setVerticalGroup(
            jPanelCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCrime, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jPanelNovels.setBackground(new java.awt.Color(40, 47, 93));

        jLabelNovels.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNovels.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNovels.setText("Novelas");

        javax.swing.GroupLayout jPanelNovelsLayout = new javax.swing.GroupLayout(jPanelNovels);
        jPanelNovels.setLayout(jPanelNovelsLayout);
        jPanelNovelsLayout.setHorizontalGroup(
            jPanelNovelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNovelsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNovels, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelNovelsLayout.setVerticalGroup(
            jPanelNovelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNovels, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        jLabelSomeAvailableBooks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSomeAvailableBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSomeAvailableBooks.setText("Algunos de nuestros títulos disponibles");

        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabelPaula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPaula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPaula.setText("El amante Japonés");

        jLabelRomeoYJulieta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRomeoYJulieta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRomeoYJulieta.setText("Romeo y Julieta");

        jLabelJaneEyre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelJaneEyre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJaneEyre.setText("Jane Eyre");

        jLabelElExtranjeroPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelElExtranjeroPrice.setForeground(new java.awt.Color(255, 82, 73));
        jLabelElExtranjeroPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelElExtranjeroPrice.setText("$25.000");
        jLabelElExtranjeroPrice.setAlignmentY(0.0F);

        jLabelPaulaPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPaulaPrice.setForeground(new java.awt.Color(0, 153, 153));
        jLabelPaulaPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPaulaPrice.setText("$42.000");
        jLabelPaulaPrice.setAlignmentY(0.0F);

        jLabelRomeoYJulietaPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRomeoYJulietaPrice.setForeground(new java.awt.Color(255, 82, 73));
        jLabelRomeoYJulietaPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRomeoYJulietaPrice.setText("$15.000");
        jLabelRomeoYJulietaPrice.setAlignmentY(0.0F);

        jLabelJaneEyrePrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelJaneEyrePrice.setForeground(new java.awt.Color(255, 82, 73));
        jLabelJaneEyrePrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJaneEyrePrice.setText("$25.000");
        jLabelJaneEyrePrice.setAlignmentY(0.0F);

        jPanelRightsReserved.setBackground(new java.awt.Color(40, 47, 93));
        jPanelRightsReserved.setAlignmentX(0.0F);
        jPanelRightsReserved.setAlignmentY(0.0F);

        jLabelRightsReserved.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabelRightsReserved.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRightsReserved.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRightsReserved.setText("© Todos los derechos reservados. 2019.");

        javax.swing.GroupLayout jPanelRightsReservedLayout = new javax.swing.GroupLayout(jPanelRightsReserved);
        jPanelRightsReserved.setLayout(jPanelRightsReservedLayout);
        jPanelRightsReservedLayout.setHorizontalGroup(
            jPanelRightsReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightsReservedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRightsReserved, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelFacebookIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelInstagramIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTwitterIconB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanelRightsReservedLayout.setVerticalGroup(
            jPanelRightsReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRightsReservedLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabelRightsReserved)
                .addContainerGap())
            .addComponent(jLabelFacebookIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelInstagramIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTwitterIconB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelIfIStayAuthor.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabelIfIStayAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIfIStayAuthor.setText("Gayle Forman");

        jLabelElExtranjeroAuthor.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabelElExtranjeroAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelElExtranjeroAuthor.setText("Albert Camus");

        jLabelPaulaAuthor.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabelPaulaAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPaulaAuthor.setText("Isabel Allende");

        jLabelRomeoYJulietaAuthor.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabelRomeoYJulietaAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRomeoYJulietaAuthor.setText("William Shakespeare");

        jLabelJaneEyreAuthor.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabelJaneEyreAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJaneEyreAuthor.setText("Charlotte Bronte");

        jPanelMonthlyFindings.setBackground(new java.awt.Color(0, 153, 153));

        jLabelFindings.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFindings.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFindings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFindings.setText("Nuestros recomendados ");

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );

        jLabelFindingsPeerOfBooks.setFont(new java.awt.Font("Tahoma", 2, 9)); // NOI18N
        jLabelFindingsPeerOfBooks.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFindingsPeerOfBooks.setText("Charlie y la fábrica de chocolate");

        javax.swing.GroupLayout jPanelMonthlyFindingsLayout = new javax.swing.GroupLayout(jPanelMonthlyFindings);
        jPanelMonthlyFindings.setLayout(jPanelMonthlyFindingsLayout);
        jPanelMonthlyFindingsLayout.setHorizontalGroup(
            jPanelMonthlyFindingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMonthlyFindingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMonthlyFindingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFindings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelMonthlyFindingsLayout.createSequentialGroup()
                        .addGroup(jPanelMonthlyFindingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelFindingsPeerOfBooks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addGroup(jPanelMonthlyFindingsLayout.createSequentialGroup()
                                .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelMonthlyFindingsLayout.setVerticalGroup(
            jPanelMonthlyFindingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMonthlyFindingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFindings, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMonthlyFindingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelFindingsPeerOfBooks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelElExtranjero.setBackground(new java.awt.Color(50, 40, 30));
        jLabelElExtranjero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelElExtranjero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelElExtranjero.setText("El extranjero");

        jLabelIfIStay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelIfIStay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIfIStay.setText("If I Stay");

        jLabelElExtranjeroPrice1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelElExtranjeroPrice1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelElExtranjeroPrice1.setForeground(new java.awt.Color(255, 82, 73));
        jLabelElExtranjeroPrice1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelElExtranjeroPrice1.setText("$20.000");
        jLabelElExtranjeroPrice1.setAlignmentY(0.0F);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Todos los medios de pago");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBookota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelRightsReserved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelShoppingCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelWishList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelSomeAvailableBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelIfIStayAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelIfIStay, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelElExtranjeroPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(88, 88, 88)
                                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelElExtranjeroAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelElExtranjero, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelElExtranjeroPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(71, 71, 71)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPaulaAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPaula)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabelPaulaPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelRomeoYJulietaAuthor, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelRomeoYJulieta, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelRomeoYJulietaPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelJaneEyre, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelJaneEyreAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelJaneEyrePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(37, 37, 37)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanelUniversal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanelYoungAdultLiterature, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanelFantasy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanelRomance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanelCrime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanelNovels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanelMonthlyFindings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelMenuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelCategories)
                                    .addGap(45, 45, 45)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabelPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelBookota, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelShoppingCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelWishList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelMenuIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSomeAvailableBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelJaneEyre)
                                    .addComponent(jLabelIfIStay, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabelRomeoYJulieta)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelRomeoYJulietaAuthor, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelJaneEyreAuthor)))
                                    .addComponent(jLabelIfIStayAuthor, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 2, Short.MAX_VALUE)
                                        .addComponent(jLabelElExtranjeroPrice1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelRomeoYJulietaPrice)
                                            .addComponent(jLabelJaneEyrePrice))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelElExtranjero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelPaula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelElExtranjeroAuthor)
                                    .addComponent(jLabelPaulaAuthor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPaulaPrice)
                                    .addComponent(jLabelElExtranjeroPrice))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelUniversal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelYoungAdultLiterature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelFantasy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelRomance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCrime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelNovels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelMonthlyFindings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)))
                .addComponent(jPanelRightsReserved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setViewportView(jTextPaneSearch1);

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHeaderPurple.setBackground(new java.awt.Color(40, 47, 93));
        jPanelHeaderPurple.setPreferredSize(new java.awt.Dimension(467, 95));
        jPanelHeaderPurple.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHeaderFreeShipping.setBackground(new java.awt.Color(255, 153, 51));
        jPanelHeaderFreeShipping.setPreferredSize(new java.awt.Dimension(449, 34));

        jLabelFreeShipping1.setBackground(new java.awt.Color(255, 37, 69));
        jLabelFreeShipping1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFreeShipping1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFreeShipping1.setText("Envíos gratis en Bogotá. Pedidos con duración máxima de envío de 24 horas.");
        jLabelFreeShipping1.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanelHeaderFreeShippingLayout = new javax.swing.GroupLayout(jPanelHeaderFreeShipping);
        jPanelHeaderFreeShipping.setLayout(jPanelHeaderFreeShippingLayout);
        jPanelHeaderFreeShippingLayout.setHorizontalGroup(
            jPanelHeaderFreeShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderFreeShippingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFreeShipping1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanelHeaderFreeShippingLayout.setVerticalGroup(
            jPanelHeaderFreeShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderFreeShippingLayout.createSequentialGroup()
                .addComponent(jLabelFreeShipping1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelHeaderPurple.add(jPanelHeaderFreeShipping, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 999, 30));

        btnHome.setBorder(null);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanelHeaderPurple.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 40, 40));
        jPanelHeaderPurple.add(jLabelAppLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 33, 39));

        jPanel2.add(jPanelHeaderPurple, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 860, 80));

        jPanel7.setBackground(new java.awt.Color(40, 47, 93));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("© Todos los derechos reservados. 2019.");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFacebookIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelInstagramIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTwitterIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelFacebookIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelInstagramIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTwitterIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 999, -1));

        jlabelBookTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelBookTitle.setText("empty");
        jPanel2.add(jlabelBookTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 480, -1));

        jlabelEditorial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabelEditorial.setText("Editorial:");
        jPanel2.add(jlabelEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jlabelAuthor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabelAuthor.setText("Autor:");
        jPanel2.add(jlabelAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        jLabelDataSheet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDataSheet.setText("Ficha técnica");
        jPanel2.add(jLabelDataSheet, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        jLabelAddToWishList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelAddToWishList.setText("Agregar a Mis Deseos");
        jPanel2.add(jLabelAddToWishList, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        jLabelPurchasing.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPurchasing.setText("Comprar");
        jPanel2.add(jLabelPurchasing, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, -1, -1));

        jlabelGenre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabelGenre.setText("Genero:");
        jPanel2.add(jlabelGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));

        jlabelBookGenre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabelBookGenre.setText("empty");
        jPanel2.add(jlabelBookGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 140, -1));

        jlabelBookEditorial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabelBookEditorial.setText("empty");
        jPanel2.add(jlabelBookEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 170, -1));

        jlabelBookAuthor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabelBookAuthor.setText("empty");
        jPanel2.add(jlabelBookAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 160, -1));

        jlabelCover.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabelCover.setText("Encuadernación:");
        jPanel2.add(jlabelCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        jlabelBookCover.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabelBookCover.setText("empty");
        jPanel2.add(jlabelBookCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 130, -1));
        jPanel2.add(jLabelBookCoverPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 220, 310));

        jlabelPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabelPrice.setForeground(new java.awt.Color(255, 82, 73));
        jlabelPrice.setText("Precio:");
        jPanel2.add(jlabelPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 262, -1, -1));

        jlabelBookPrice.setBackground(new java.awt.Color(40, 47, 93));
        jlabelBookPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabelBookPrice.setForeground(new java.awt.Color(255, 82, 73));
        jlabelBookPrice.setText("empty");
        jPanel2.add(jlabelBookPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 90, -1));

        jlabelISBNCode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabelISBNCode.setText("ISBN:");
        jPanel2.add(jlabelISBNCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        jlabelBookISBNCode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabelBookISBNCode.setText("empty");
        jPanel2.add(jlabelBookISBNCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 140, -1));

        jlabelPages.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabelPages.setText("Numero de paginas:");
        jPanel2.add(jlabelPages, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));

        jlabelBookPages.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabelBookPages.setText("empty");
        jPanel2.add(jlabelBookPages, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 120, -1));

        jlabelStock.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabelStock.setText("Stock:");
        jPanel2.add(jlabelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jlabelBookStock.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabelBookStock.setText("empty");
        jPanel2.add(jlabelBookStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        jButtonShoppingCart.setBackground(new java.awt.Color(40, 47, 93));
        jButtonShoppingCart.setForeground(new java.awt.Color(250, 250, 250));
        jButtonShoppingCart.setText("Mis compras");
        jButtonShoppingCart.setBorder(null);
        jButtonShoppingCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonShoppingCartMouseEntered(evt);
            }
        });
        jButtonShoppingCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShoppingCartActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonShoppingCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 410, 40));

        jlabelBookTitle1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabelBookTitle1.setText("Sinopsis:");
        jPanel2.add(jlabelBookTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));

        jButtonAddToWishList.setBorder(null);
        jButtonAddToWishList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAddToWishListMouseEntered(evt);
            }
        });
        jButtonAddToWishList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddToWishListActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAddToWishList, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 50, 50));

        jButtonBuyBook.setBorder(null);
        jButtonBuyBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBuyBookMouseEntered(evt);
            }
        });
        jButtonBuyBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuyBookActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBuyBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 50, 50));

        jButtonMyWishes.setBackground(new java.awt.Color(40, 43, 97));
        jButtonMyWishes.setForeground(new java.awt.Color(250, 250, 250));
        jButtonMyWishes.setText("Mis  deseos");
        jButtonMyWishes.setBorder(null);
        jButtonMyWishes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMyWishesMouseEntered(evt);
            }
        });
        jButtonMyWishes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMyWishesActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonMyWishes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 400, 40));
        jPanel2.add(jLabelAppLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, -1));

        jScrollPane3.setBorder(null);

        txtpaneSynopsis.setEditable(false);
        txtpaneSynopsis.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jScrollPane3.setViewportView(txtpaneSynopsis);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 310, 290));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        BookStore.close(rootPane);
    }//GEN-LAST:event_formWindowClosing

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        setVisible(false);
        MainWindow mainWindow = new MainWindow();
        mainWindow.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void jButtonShoppingCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShoppingCartActionPerformed
        if (BookStore.getUsersMap().get(LogInWindow.getUserName()).getShoppingCart().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Su carrito de compras está vacio", "", JOptionPane.WARNING_MESSAGE);
        } else {
            setVisible(false);
            ShoppingCartWindow shoppingCartWindow = new ShoppingCartWindow();
            shoppingCartWindow.setVisible(true);
        }
    }//GEN-LAST:event_jButtonShoppingCartActionPerformed

    private void jButtonBuyBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuyBookActionPerformed
        if (BookStore.getUsersMap().get(LogInWindow.getUserName()).getShoppingCart().contains(book)) {
            JOptionPane.showMessageDialog(rootPane, "Este ya se encuentra en\nsu carrito de compras. Escoja otro", "", JOptionPane.WARNING_MESSAGE);
        } else {
            BookStore.getUsersMap().get(LogInWindow.getUserName()).getShoppingCart().add(book);
            JOptionPane.showMessageDialog(rootPane, "Libro agregado al\nsu carrito de compras", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuyBookActionPerformed

    private void jButtonAddToWishListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddToWishListActionPerformed
        if (BookStore.getUsersMap().get(LogInWindow.getUserName()).getWishList().contains(book)) {
            JOptionPane.showMessageDialog(rootPane, "Este ya se encuentra en\nsu lista de deseos. Escoja otro", "", JOptionPane.WARNING_MESSAGE);
        } else if (BookStore.getUsersMap().get(LogInWindow.getUserName()).getShoppingCart().contains(book)) {
            JOptionPane.showMessageDialog(rootPane, "Este ya se encuentra en\nsu carrito de compras. Escoja otro", "", JOptionPane.WARNING_MESSAGE);
        } else {
            BookStore.getUsersMap().get(LogInWindow.getUserName()).getWishList().add(book);
            JOptionPane.showMessageDialog(rootPane, "Libro agregado a \nsu lista de deseos", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAddToWishListActionPerformed

    private void jButtonMyWishesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMyWishesActionPerformed
        if (BookStore.getUsersMap().get(LogInWindow.getUserName()).getWishList().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Su lista de deseos está vacia", "", JOptionPane.WARNING_MESSAGE);
        } else {
            setVisible(false);
            WishListWindow wishListWindow = new WishListWindow();
            wishListWindow.setVisible(true);
        }
    }//GEN-LAST:event_jButtonMyWishesActionPerformed

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        btnHome.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void jButtonMyWishesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMyWishesMouseEntered
        jButtonMyWishes.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_jButtonMyWishesMouseEntered

    private void jButtonShoppingCartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonShoppingCartMouseEntered
        jButtonShoppingCart.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_jButtonShoppingCartMouseEntered

    private void jButtonAddToWishListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddToWishListMouseEntered
        jButtonAddToWishList.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_jButtonAddToWishListMouseEntered

    private void jButtonBuyBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuyBookMouseEntered
        jButtonBuyBook.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_jButtonBuyBookMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookViewWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookViewWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookViewWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookViewWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BookViewWindow().setVisible(true);
                } catch (IOException ex) {

                }
            }
        });
    }

    public static Book getBook() {
        return book;
    }

    public static void setBook(Book book) {
        BookViewWindow.book = book;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton jButtonAddToWishList;
    private javax.swing.JButton jButtonBuyBook;
    private javax.swing.JButton jButtonMyWishes;
    private javax.swing.JButton jButtonShoppingCart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAddToWishList;
    private javax.swing.JLabel jLabelAppLogo;
    private javax.swing.JLabel jLabelAppLogo1;
    private javax.swing.JLabel jLabelAppLogo2;
    private javax.swing.JLabel jLabelBookCoverPage;
    private javax.swing.JLabel jLabelCategories;
    private javax.swing.JLabel jLabelCrime;
    private javax.swing.JLabel jLabelDataSheet;
    private javax.swing.JLabel jLabelElExtranjero;
    private javax.swing.JLabel jLabelElExtranjeroAuthor;
    private javax.swing.JLabel jLabelElExtranjeroPrice;
    private javax.swing.JLabel jLabelElExtranjeroPrice1;
    private javax.swing.JLabel jLabelFacebookIcon;
    private javax.swing.JLabel jLabelFacebookIcon2;
    private javax.swing.JLabel jLabelFantasy;
    private javax.swing.JLabel jLabelFindings;
    private javax.swing.JLabel jLabelFindingsPeerOfBooks;
    private javax.swing.JLabel jLabelFreeShipping;
    private javax.swing.JLabel jLabelFreeShipping1;
    private javax.swing.JLabel jLabelHomeIcon;
    private javax.swing.JLabel jLabelIfIStay;
    private javax.swing.JLabel jLabelIfIStayAuthor;
    private javax.swing.JLabel jLabelInstagramIcon;
    private javax.swing.JLabel jLabelInstagramIcon2;
    private javax.swing.JLabel jLabelJaneEyre;
    private javax.swing.JLabel jLabelJaneEyreAuthor;
    private javax.swing.JLabel jLabelJaneEyrePrice;
    private javax.swing.JLabel jLabelMenuIcon;
    private javax.swing.JLabel jLabelMiAccount;
    private javax.swing.JLabel jLabelNovels;
    private javax.swing.JLabel jLabelPaula;
    private javax.swing.JLabel jLabelPaulaAuthor;
    private javax.swing.JLabel jLabelPaulaPrice;
    private javax.swing.JLabel jLabelPayment;
    private javax.swing.JLabel jLabelPurchasing;
    private javax.swing.JLabel jLabelRightsReserved;
    private javax.swing.JLabel jLabelRomance;
    private javax.swing.JLabel jLabelRomeoYJulieta;
    private javax.swing.JLabel jLabelRomeoYJulietaAuthor;
    private javax.swing.JLabel jLabelRomeoYJulietaPrice;
    private javax.swing.JLabel jLabelShoppingC;
    private javax.swing.JLabel jLabelShoppingCart;
    private javax.swing.JLabel jLabelSomeAvailableBooks;
    private javax.swing.JLabel jLabelTwitterIcon2;
    private javax.swing.JLabel jLabelTwitterIconB;
    private javax.swing.JLabel jLabelUniversal;
    private javax.swing.JLabel jLabelWishList;
    private javax.swing.JLabel jLabelWishListIcon;
    private javax.swing.JLabel jLabelYoungAdultLiterature;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBookota;
    private javax.swing.JPanel jPanelCrime;
    private javax.swing.JPanel jPanelFantasy;
    private javax.swing.JPanel jPanelFreeShipping;
    private javax.swing.JPanel jPanelHeaderFreeShipping;
    private javax.swing.JPanel jPanelHeaderPurple;
    private javax.swing.JPanel jPanelMonthlyFindings;
    private javax.swing.JPanel jPanelNovels;
    private javax.swing.JPanel jPanelRightsReserved;
    private javax.swing.JPanel jPanelRomance;
    private javax.swing.JPanel jPanelShoppingCart;
    private javax.swing.JPanel jPanelUniversal;
    private javax.swing.JPanel jPanelWishList;
    private javax.swing.JPanel jPanelYoungAdultLiterature;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPaneSearch;
    private javax.swing.JTextPane jTextPaneSearch1;
    private javax.swing.JLabel jlabelAuthor;
    private javax.swing.JLabel jlabelBookAuthor;
    private javax.swing.JLabel jlabelBookCover;
    private javax.swing.JLabel jlabelBookEditorial;
    private javax.swing.JLabel jlabelBookGenre;
    private javax.swing.JLabel jlabelBookISBNCode;
    private javax.swing.JLabel jlabelBookPages;
    private javax.swing.JLabel jlabelBookPrice;
    private javax.swing.JLabel jlabelBookStock;
    private javax.swing.JLabel jlabelBookTitle;
    private javax.swing.JLabel jlabelBookTitle1;
    private javax.swing.JLabel jlabelCover;
    private javax.swing.JLabel jlabelEditorial;
    private javax.swing.JLabel jlabelGenre;
    private javax.swing.JLabel jlabelISBNCode;
    private javax.swing.JLabel jlabelPages;
    private javax.swing.JLabel jlabelPrice;
    private javax.swing.JLabel jlabelStock;
    private javax.swing.JTextPane txtpaneSynopsis;
    // End of variables declaration//GEN-END:variables
}
