package UI;

import businessLogic.BookStore;
import businessLogic.ExceptionManager;
import data.Book;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class CreditCardWindow extends javax.swing.JFrame {

    public CreditCardWindow() {
        initComponents();

        setTitle("\ud83d\udcda Bookotá");
        setIconImage(new ImageIcon(getClass().getResource("/Imagen/Bookota.png")).getImage());
        setLocationRelativeTo(null);

        ImageIcon imagen1 = new ImageIcon(getClass().getResource("/Imagen/Visa.jpg"));
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(btnVisa.getWidth(), btnVisa.getHeight(), Image.SCALE_SMOOTH));
        btnVisa.setIcon(fondo1);
        this.repaint();

        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/Imagen/MasterCard.jpg"));
        Icon fondo2 = new ImageIcon(imagen2.getImage().getScaledInstance(btnMastercard.getWidth(), btnMastercard.getHeight(), Image.SCALE_SMOOTH));
        btnMastercard.setIcon(fondo2);
        this.repaint();

        ImageIcon imagen3 = new ImageIcon(getClass().getResource("/Imagen/AmericanExpress.jpg"));
        Icon fondo3 = new ImageIcon(imagen3.getImage().getScaledInstance(btnAmericanExpress.getWidth(), btnAmericanExpress.getHeight(), Image.SCALE_SMOOTH));
        btnAmericanExpress.setIcon(fondo3);
        this.repaint();

        ImageIcon imagen4 = new ImageIcon(getClass().getResource("/Imagen/DinersClub.jpg"));
        Icon fondo4 = new ImageIcon(imagen4.getImage().getScaledInstance(btnDinersClub.getWidth(), btnDinersClub.getHeight(), Image.SCALE_SMOOTH));
        btnDinersClub.setIcon(fondo4);
        this.repaint();

        ImageIcon imagen5 = new ImageIcon(getClass().getResource("/Imagen/Codensa.png"));
        Icon fondo5 = new ImageIcon(imagen5.getImage().getScaledInstance(btnCodensa.getWidth(), btnCodensa.getHeight(), Image.SCALE_SMOOTH));
        btnCodensa.setIcon(fondo5);
        this.repaint();

        ImageIcon imagen6 = new ImageIcon(getClass().getResource("/Imagen/CompraSegura.png"));
        Icon fondo6 = new ImageIcon(imagen6.getImage().getScaledInstance(imageIconLock.getWidth(), imageIconLock.getHeight(), Image.SCALE_SMOOTH));
        imageIconLock.setIcon(fondo6);
        this.repaint();

        if (BookStore.getUsersMap().get(LogInWindow.getUserName()).getRememberCreditCardData()) {
            cbxCardTypes.setSelectedItem(BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().get(0));
            txtCardOwner.setText(BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().get(1));
            cbxIdTypes.setSelectedItem(BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().get(2));
            txtId.setText(BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().get(3));
            txtCardNumber.setText(BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().get(4));
            txtCardCode.setText(BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().get(5));
            cbxYear.setSelectedItem(BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().get(6));
            cbxMonth.setSelectedItem(BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().get(7));
            cbxDues.setSelectedItem(BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().get(8));
            txtPhoneNumber.setText(BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().get(9));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        imageIconLock = new javax.swing.JLabel();
        btnVisa = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbxIdTypes = new javax.swing.JComboBox<>();
        txtId = new javax.swing.JTextField();
        txtCardCode = new javax.swing.JTextField();
        cbxMonth = new javax.swing.JComboBox<>();
        cbxYear = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbxDues = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        checkboxTyC = new javax.swing.JCheckBox();
        checkboxRemember = new javax.swing.JCheckBox();
        btnBuy = new javax.swing.JButton();
        btnMastercard = new javax.swing.JButton();
        btnAmericanExpress = new javax.swing.JButton();
        btnDinersClub = new javax.swing.JButton();
        btnCodensa = new javax.swing.JButton();
        txtCardNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCardOwner = new javax.swing.JTextField();
        btnReturn = new javax.swing.JButton();
        cbxCardTypes = new javax.swing.JComboBox<>();

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(40, 47, 93));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("© Todos los derechos reservados. 2019.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));

        jPanel5.setBackground(new java.awt.Color(40, 47, 93));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tarjeta de crédito");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Compra segura");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageIconLock, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(217, 217, 217))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(imageIconLock, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnVisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Visa.jpg"))); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Titular de la tarjeta *");
        jLabel7.setAlignmentY(0.0F);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Documento de identificación*");
        jLabel8.setAlignmentY(0.0F);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Número de la tarjeta *");
        jLabel9.setAlignmentY(0.0F);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Código de seguridad *");
        jLabel10.setAlignmentY(0.0F);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Fecha de Vencimiento*");
        jLabel11.setAlignmentY(0.0F);

        cbxIdTypes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "CE", "Pasaporte", "NIT" }));
        cbxIdTypes.setAlignmentX(0.0F);
        cbxIdTypes.setAlignmentY(0.0F);

        txtId.setAlignmentX(0.0F);
        txtId.setAlignmentY(0.0F);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtCardCode.setAlignmentX(0.0F);
        txtCardCode.setAlignmentY(0.0F);
        txtCardCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardCodeActionPerformed(evt);
            }
        });

        cbxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbxMonth.setAlignmentX(0.0F);
        cbxMonth.setAlignmentY(0.0F);

        cbxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022" }));
        cbxYear.setAlignmentX(0.0F);
        cbxYear.setAlignmentY(0.0F);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Cuotas*");
        jLabel12.setAlignmentY(0.0F);

        cbxDues.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "3", "6", "12", "14", "18", "24", "36", "48" }));
        cbxDues.setAlignmentX(0.0F);
        cbxDues.setAlignmentY(0.0F);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Teléfono celular *");
        jLabel13.setAlignmentY(0.0F);

        txtPhoneNumber.setAlignmentX(0.0F);
        txtPhoneNumber.setAlignmentY(0.0F);
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        checkboxTyC.setText("Acepto los términos y condiciones y políticas de privacidad");

        checkboxRemember.setText("Recordar mis datos para futuros pagos");

        btnBuy.setText("Pagar");
        btnBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuyMouseEntered(evt);
            }
        });
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        txtCardNumber.setAlignmentX(0.0F);
        txtCardNumber.setAlignmentY(0.0F);
        txtCardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardNumberActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo de tarjeta *");

        txtCardOwner.setAlignmentX(0.0F);
        txtCardOwner.setAlignmentY(0.0F);
        txtCardOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardOwnerActionPerformed(evt);
            }
        });

        btnReturn.setText("Volver");
        btnReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReturnMouseEntered(evt);
            }
        });
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        cbxCardTypes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VISA", "MasterCard", "American Express", "Diners Club", "Codensa" }));
        cbxCardTypes.setLightWeightPopupEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnVisa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnMastercard, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnAmericanExpress, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnDinersClub, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnCodensa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel5)
                .addGap(16, 16, 16)
                .addComponent(cbxCardTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCardOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCardCode, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(cbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxDues, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkboxRemember)
                    .addComponent(checkboxTyC)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(btnBuy)
                .addGap(19, 19, 19)
                .addComponent(btnReturn))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(cbxIdTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addComponent(txtId))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMastercard, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAmericanExpress, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDinersClub, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCodensa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbxCardTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(txtCardOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbxIdTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addComponent(txtCardCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11))
                    .addComponent(cbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12))
                    .addComponent(cbxDues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel13))
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(checkboxRemember))
                    .addComponent(checkboxTyC))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuy)
                    .addComponent(btnReturn))
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtCardCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardCodeActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtCardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardNumberActionPerformed

    private void txtCardOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardOwnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardOwnerActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        setVisible(false);
        FinishPurchaseWindow finishPurchaseWindow = new FinishPurchaseWindow();
        finishPurchaseWindow.setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        BookStore.close(rootPane);
    }//GEN-LAST:event_formWindowClosing

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        String cardType, cardOwner, idType, id, cardNumber, cardCode, year, month, dues, phoneNumber;
        cardType = (String) cbxCardTypes.getSelectedItem();
        cardOwner = txtCardOwner.getText();
        idType = (String) cbxIdTypes.getSelectedItem();
        id = txtId.getText();
        cardNumber = txtCardNumber.getText();
        cardCode = txtCardCode.getText();
        year = (String) cbxYear.getSelectedItem();
        month = (String) cbxMonth.getSelectedItem();
        dues = (String) cbxDues.getSelectedItem();
        phoneNumber = txtPhoneNumber.getText();
        if (cardOwner.length() == 0 || id.length() == 0 || cardNumber.length() == 0
                || cardCode.length() == 0 || phoneNumber.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Por favor llene todos los campos", "", JOptionPane.ERROR_MESSAGE);
        } else if (ExceptionManager.checkIntegerValue(txtId) || ExceptionManager.checkIntegerValue(txtCardNumber)
                || ExceptionManager.checkIntegerValue(txtCardCode) || ExceptionManager.checkIntegerValue(txtPhoneNumber)) {
            JOptionPane.showMessageDialog(rootPane, "Por favor llene correctamente los campos", "", JOptionPane.ERROR_MESSAGE);
        } else {
            if (checkboxTyC.isSelected()) {
                if (checkboxRemember.isSelected()) {
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().clear();
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add(cardType);
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add(cardOwner);
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add(idType);
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add(id);
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add(cardNumber);
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add(cardCode);
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add(year);
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add(month);
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add(dues);
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add(phoneNumber);
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).setRememberCreditCardData(true);
                } else {
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().clear();
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add("");
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add("");
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add("");
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add("");
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add("");
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add("");
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add("");
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add("");
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add("");
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).getPayPalPaying().add("");
                    BookStore.getUsersMap().get(LogInWindow.getUserName()).setRememberCreditCardData(false);
                }
                JOptionPane.showMessageDialog(rootPane, "Gracias por su compra", "", JOptionPane.INFORMATION_MESSAGE);
                setVisible(false);
                for (Book book : BookStore.getUsersMap().get(LogInWindow.getUserName()).getShoppingCart()) {
                    if (BookStore.getUsersMap().get(LogInWindow.getUserName()).getWishList().contains(book)) {
                        BookStore.getUsersMap().get(LogInWindow.getUserName()).getWishList().remove(book);
                    }
                    int bookStock = BookStore.getBooksMap().get(book.getIndex()).getStock();
                    if (bookStock == 1) {
                        BookStore.getBooksMap().remove(book.getIndex());
                    }
                    BookStore.getBooksMap().get(book.getIndex()).setStock(bookStock - 1);
                }
                BookStore.getUsersMap().get(LogInWindow.getUserName()).getShoppingCart().clear();
                MainWindow mainWindow = new MainWindow();
                mainWindow.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Por favor marque la casilla de TyC", "", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBuyActionPerformed

    private void btnBuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyMouseEntered
        btnBuy.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnBuyMouseEntered

    private void btnReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseEntered
        btnReturn.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnReturnMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditCardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditCardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditCardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditCardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditCardWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmericanExpress;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnCodensa;
    private javax.swing.JButton btnDinersClub;
    private javax.swing.JButton btnMastercard;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnVisa;
    private javax.swing.JComboBox<String> cbxCardTypes;
    private javax.swing.JComboBox<String> cbxDues;
    private javax.swing.JComboBox<String> cbxIdTypes;
    private javax.swing.JComboBox<String> cbxMonth;
    private javax.swing.JComboBox<String> cbxYear;
    private javax.swing.JCheckBox checkboxRemember;
    private javax.swing.JCheckBox checkboxTyC;
    private javax.swing.JLabel imageIconLock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtCardCode;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtCardOwner;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
