package UI;

import businessLogic.BookStore;
import data.User;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class MyAccountWindow extends javax.swing.JFrame {

    public MyAccountWindow() {
        initComponents();

        setTitle("\ud83d\udcda Bookotá");
        setIconImage(new ImageIcon(getClass().getResource("/Imagen/Bookota.png")).getImage());
        setLocationRelativeTo(null);

        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/Imagen/imageIconInformation.png"));
        Icon fondo2 = new ImageIcon(imagen2.getImage().getScaledInstance(imageIconInfo.getWidth(), imageIconInfo.getHeight(), Image.SCALE_SMOOTH));
        imageIconInfo.setIcon(fondo2);
        this.repaint();

        ImageIcon imagen3 = new ImageIcon(getClass().getResource("/Imagen/Facebook.png"));
        Icon fondo3 = new ImageIcon(imagen3.getImage().getScaledInstance(imageIconFacebook1.getWidth(), imageIconFacebook1.getHeight(), Image.SCALE_SMOOTH));
        imageIconFacebook1.setIcon(fondo3);
        this.repaint();

        ImageIcon imagen4 = new ImageIcon(getClass().getResource("/Imagen/Instagram.png"));
        Icon fondo4 = new ImageIcon(imagen4.getImage().getScaledInstance(imageIconInstagram1.getWidth(), imageIconInstagram1.getHeight(), Image.SCALE_SMOOTH));
        imageIconInstagram1.setIcon(fondo4);
        this.repaint();

        ImageIcon imagen5 = new ImageIcon(getClass().getResource("/Imagen/Twitter.png"));
        Icon fondo5 = new ImageIcon(imagen5.getImage().getScaledInstance(imageIconTwitter1.getWidth(), imageIconTwitter1.getHeight(), Image.SCALE_SMOOTH));
        imageIconTwitter1.setIcon(fondo5);
        this.repaint();

        updateInfo();
        setEditableOrNot(false);
        btnSaveChanges.setEnabled(false);
    }

    private void setEditableOrNot(boolean status) {
        cbxGenres.setEnabled(status);
        txtName.setEditable(status);
        txtUserName.setEditable(status);
        txtPassword.setEditable(status);
        txtEmail.setEditable(status);
        txtAdress.setEditable(status);
    }

    private void updateInfo() {
        txtName.setText(BookStore.getUsersMap().get(LogInWindow.getUserName()).getName());
        txtUserName.setText(BookStore.getUsersMap().get(LogInWindow.getUserName()).getUsername());
        txtPassword.setText(BookStore.getUsersMap().get(LogInWindow.getUserName()).getPassword());
        txtEmail.setText(BookStore.getUsersMap().get(LogInWindow.getUserName()).getEmail());
        txtAdress.setText(BookStore.getUsersMap().get(LogInWindow.getUserName()).getHomeAdress());
        cbxGenres.setSelectedItem(BookStore.getUsersMap().get(LogInWindow.getUserName()).getFavouriteGenre());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        PanelBackground = new javax.swing.JPanel();
        jPanelRightsReserved = new javax.swing.JPanel();
        txtRightsReserved = new javax.swing.JLabel();
        imageIconTwitter1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        imageIconInstagram1 = new javax.swing.JLabel();
        imageIconFacebook1 = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        jPanelCenterBackground = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        imageIconInfo = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAdress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        bntChangeInfo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jlabelPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnSaveChanges = new javax.swing.JButton();
        cbxGenres = new javax.swing.JComboBox<>();
        jLabelLeftSideBanner = new javax.swing.JLabel();
        jLabelRightSideBanner = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRightsReserved.setBackground(new java.awt.Color(40, 47, 93));
        jPanelRightsReserved.setAlignmentX(0.0F);
        jPanelRightsReserved.setAlignmentY(0.0F);

        txtRightsReserved.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtRightsReserved.setForeground(new java.awt.Color(255, 255, 255));
        txtRightsReserved.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRightsReserved.setText("© Todos los derechos reservados. 2019.");

        javax.swing.GroupLayout jPanelRightsReservedLayout = new javax.swing.GroupLayout(jPanelRightsReserved);
        jPanelRightsReserved.setLayout(jPanelRightsReservedLayout);
        jPanelRightsReservedLayout.setHorizontalGroup(
            jPanelRightsReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightsReservedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtRightsReserved, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageIconFacebook1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(imageIconInstagram1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imageIconTwitter1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelRightsReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRightsReservedLayout.createSequentialGroup()
                    .addContainerGap(311, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );
        jPanelRightsReservedLayout.setVerticalGroup(
            jPanelRightsReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightsReservedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRightsReserved)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(imageIconFacebook1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(imageIconInstagram1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(imageIconTwitter1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelRightsReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRightsReservedLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanelHeader.setBackground(new java.awt.Color(40, 47, 93));

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        jPanelCenterBackground.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCenterBackground.setAlignmentX(0.0F);
        jPanelCenterBackground.setAlignmentY(0.0F);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Correo electrónico:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Dirección:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Género favorito:");

        txtName.setEditable(false);

        txtEmail.setEditable(false);

        txtAdress.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Mi información");

        btnReturn.setText("Regresar");
        btnReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReturnMouseEntered(evt);
            }
        });
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        bntChangeInfo.setText("Cambiar información");
        bntChangeInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntChangeInfoMouseEntered(evt);
            }
        });
        bntChangeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntChangeInfoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Usuario:");

        txtUserName.setEditable(false);

        jlabelPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabelPassword.setText("Contraseña:");

        txtPassword.setEditable(false);

        btnSaveChanges.setText("Guardar");
        btnSaveChanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveChangesMouseEntered(evt);
            }
        });
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        cbxGenres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Literatura Universal", "Literatura Juvenil", "Fantasía", "Romance", "Terror", "Novela" }));
        cbxGenres.setToolTipText("");
        cbxGenres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGenresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCenterBackgroundLayout = new javax.swing.GroupLayout(jPanelCenterBackground);
        jPanelCenterBackground.setLayout(jPanelCenterBackgroundLayout);
        jPanelCenterBackgroundLayout.setHorizontalGroup(
            jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterBackgroundLayout.createSequentialGroup()
                .addGroup(jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCenterBackgroundLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(btnReturn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntChangeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbxGenres, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAdress, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanelCenterBackgroundLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jlabelPassword)
                        .addGap(18, 18, 18)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCenterBackgroundLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCenterBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCenterBackgroundLayout.createSequentialGroup()
                        .addGroup(jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imageIconInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCenterBackgroundLayout.createSequentialGroup()
                        .addComponent(btnSaveChanges)
                        .addGap(66, 66, 66))))
        );
        jPanelCenterBackgroundLayout.setVerticalGroup(
            jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageIconInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxGenres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelCenterBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturn)
                    .addComponent(bntChangeInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnSaveChanges)
                .addContainerGap())
        );

        jLabelLeftSideBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/TropicalBackground.jpg"))); // NOI18N
        jLabelLeftSideBanner.setAlignmentY(0.0F);

        jLabelRightSideBanner.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelRightSideBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/TropicalBackground.jpg"))); // NOI18N
        jLabelRightSideBanner.setAlignmentY(0.0F);

        javax.swing.GroupLayout PanelBackgroundLayout = new javax.swing.GroupLayout(PanelBackground);
        PanelBackground.setLayout(PanelBackgroundLayout);
        PanelBackgroundLayout.setHorizontalGroup(
            PanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelBackgroundLayout.createSequentialGroup()
                .addComponent(jLabelLeftSideBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCenterBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRightSideBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelRightsReserved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelBackgroundLayout.setVerticalGroup(
            PanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBackgroundLayout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBackgroundLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanelCenterBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRightSideBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLeftSideBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRightsReserved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(PanelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntChangeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntChangeInfoActionPerformed
        btnSaveChanges.setEnabled(true);
        setEditableOrNot(true);
        JOptionPane.showMessageDialog(rootPane, "Ingrese sus nuevos datos\nen los campos de texto", "", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bntChangeInfoActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        
        boolean repeatedUser = false;
        String userName, name, homeAdress, email, favouriteGenre, password;
        userName = txtUserName.getText();
        name = txtName.getText();
        homeAdress = txtAdress.getText();
        email = txtEmail.getText();
        favouriteGenre = (String) cbxGenres.getSelectedItem();
        password = txtPassword.getText();

        for (User user : BookStore.getUsersMap().values()) {
            if (user.getUsername().equals(userName)) {
                repeatedUser = true;
            }
        }

        if (repeatedUser) {
            JOptionPane.showMessageDialog(rootPane, "El nombre de usuario ingresado\nya está usado", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (userName.length() > 0 && name.length() > 0 && homeAdress.length() > 0 && email.length() > 0 && password.length() > 0) {
                int answer = JOptionPane.showConfirmDialog(rootPane, "Está de seguro?", "", JOptionPane.YES_NO_OPTION);
                if (answer == 0) {
                    
                    BookStore.getUsersMap().remove(LogInWindow.getUserName());
                    
                    User newUser = new User(homeAdress, favouriteGenre, userName, password, name, email);
                    
                    LogInWindow.setUserName(userName);
                    LogInWindow.setPassword(password);
                    
                    BookStore.getUsersMap().put(userName, newUser);
                    
                    setEditableOrNot(false);
                    btnSaveChanges.setEnabled(false);
                    updateInfo();
                    JOptionPane.showMessageDialog(rootPane, "Cambios aplicados", "", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Por favor llene todos los campos", "", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        BookStore.close(rootPane);
    }//GEN-LAST:event_formWindowClosing

    private void cbxGenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGenresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxGenresActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        setVisible(false);
        MainWindow mainWindow = new MainWindow();
        mainWindow.setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseEntered
        btnReturn.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnReturnMouseEntered

    private void bntChangeInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntChangeInfoMouseEntered
        bntChangeInfo.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_bntChangeInfoMouseEntered

    private void btnSaveChangesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveChangesMouseEntered
        btnSaveChanges.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnSaveChangesMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyAccountWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyAccountWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyAccountWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyAccountWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyAccountWindow().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBackground;
    private javax.swing.JButton bntChangeInfo;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JComboBox<String> cbxGenres;
    private javax.swing.JLabel imageIconFacebook1;
    private javax.swing.JLabel imageIconInfo;
    private javax.swing.JLabel imageIconInstagram1;
    private javax.swing.JLabel imageIconTwitter1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLeftSideBanner;
    private javax.swing.JLabel jLabelRightSideBanner;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelCenterBackground;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelRightsReserved;
    private javax.swing.JLabel jlabelPassword;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JLabel txtRightsReserved;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
