/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import businessLogic.BookStore;
import data.User;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class RegisterWindow extends javax.swing.JFrame {

    public RegisterWindow() {
        initComponents();

        setTitle("\ud83d\udcda Bookotá");
        setIconImage(new ImageIcon(getClass().getResource("/Imagen/Bookota.png")).getImage());
        setLocationRelativeTo(null);

        ImageIcon imagen1 = new ImageIcon(getClass().getResource("/Imagen/User1.png"));
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(jLabelUserIconSignIn.getWidth(), jLabelUserIconSignIn.getHeight(), Image.SCALE_SMOOTH));
        jLabelUserIconSignIn.setIcon(fondo1);
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelAdreess = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JButton();
        txtAdress = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabelLeft = new javax.swing.JLabel();
        jLabelRight = new javax.swing.JLabel();
        jPanelRightsReserved = new javax.swing.JPanel();
        jLabelRightsReserved = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelUserIconSignIn = new javax.swing.JLabel();
        cbxFavouriteGenre = new javax.swing.JComboBox<>();
        jLabelUsername1 = new javax.swing.JLabel();
        pfPassword = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(40, 47, 93));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsername.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setText("Nombre");
        jPanel1.add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 155, -1, -1));

        jLabelAdreess.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAdreess.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdreess.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelAdreess.setText("Dirección");
        jPanel1.add(jLabelAdreess, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 218, -1, -1));

        jLabelGender.setBackground(new java.awt.Color(255, 255, 255));
        jLabelGender.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGender.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelGender.setText("Género favorito");
        jPanel1.add(jLabelGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 281, 88, -1));

        jLabelEmail.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelEmail.setText("E-mail");
        jPanel1.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 218, -1, -1));

        jLabelPassword.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPassword.setText("Contraseña");
        jPanel1.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 281, 88, -1));

        btnSignIn.setText("Regístrate");
        btnSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignInMouseEntered(evt);
            }
        });
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 328, -1, -1));

        txtAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 215, 120, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 215, 120, -1));

        txtName.setToolTipText("Nombre");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 152, 120, -1));

        jLabelLeft.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Laterales.jpg"))); // NOI18N
        jLabelLeft.setAlignmentY(0.0F);
        jPanel1.add(jLabelLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 85, -1));

        jLabelRight.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Laterales.jpg"))); // NOI18N
        jLabelRight.setAlignmentY(0.0F);
        jPanel1.add(jLabelRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 0, 80, -1));

        jPanelRightsReserved.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRightsReserved.setAlignmentX(0.0F);
        jPanelRightsReserved.setAlignmentY(0.0F);

        jLabelRightsReserved.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabelRightsReserved.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRightsReserved.setText("© Todos los derechos reservados. 2019.");

        javax.swing.GroupLayout jPanelRightsReservedLayout = new javax.swing.GroupLayout(jPanelRightsReserved);
        jPanelRightsReserved.setLayout(jPanelRightsReservedLayout);
        jPanelRightsReservedLayout.setHorizontalGroup(
            jPanelRightsReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightsReservedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRightsReserved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRightsReservedLayout.setVerticalGroup(
            jPanelRightsReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRightsReservedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRightsReserved)
                .addContainerGap())
        );

        jPanel1.add(jPanelRightsReserved, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 366, 677, -1));

        jPanel2.setBackground(new java.awt.Color(40, 47, 93));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(jLabelUserIconSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUserIconSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 0, -1, 106));

        cbxFavouriteGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Literatura Universal", "Literatura Juvenil", "Fantasía", "Romance", "Terror", "Novela" }));
        jPanel1.add(cbxFavouriteGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 278, 120, -1));

        jLabelUsername1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUsername1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername1.setText("Usuario");
        jPanel1.add(jLabelUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 155, -1, -1));
        jPanel1.add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 278, 120, -1));

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 152, 120, -1));

        btnReturn.setText("Volver");
        btnReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReturnMouseEntered(evt);
            }
        });
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 328, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed

    }//GEN-LAST:event_txtNameActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        boolean repeatedUser = false;
        String userName, name, homeAdress, email, favouriteGenre, password;
        userName = txtUser.getText();
        name = txtName.getText();
        homeAdress = txtAdress.getText();
        email = txtEmail.getText();
        favouriteGenre = (String) cbxFavouriteGenre.getSelectedItem();
        password = new String(pfPassword.getPassword());
        if (userName.length() > 0 && name.length() > 0 && homeAdress.length() > 0 && email.length() > 0 && password.length() > 0) {
            User newUser = new User(homeAdress, favouriteGenre, userName, password, name, email);
            if (BookStore.checkRepeatedUser(BookStore.getUsersMap(), newUser)) {
                JOptionPane.showMessageDialog(rootPane, "Usuario ya creado\nPor favor intente de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                BookStore.getUsersMap().put(userName, newUser);
                JOptionPane.showMessageDialog(rootPane, "Usuario creado exitosamente", "Usuario creado", JOptionPane.INFORMATION_MESSAGE);
                setVisible(false);
                StartWindow pantallaInicio = new StartWindow();
                pantallaInicio.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Por favor llene todos los campos", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSignInActionPerformed

    private void txtAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdressActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        setVisible(false);
        StartWindow startWindow = new StartWindow();
        startWindow.setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        BookStore.close(rootPane);
    }//GEN-LAST:event_formWindowClosing

    private void btnSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignInMouseEntered
        btnSignIn.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnSignInMouseEntered

    private void btnReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseEntered
        btnReturn.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btnReturnMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JComboBox<String> cbxFavouriteGenre;
    private javax.swing.JLabel jLabelAdreess;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelLeft;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelRight;
    private javax.swing.JLabel jLabelRightsReserved;
    private javax.swing.JLabel jLabelUserIconSignIn;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelUsername1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelRightsReserved;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
