package UI;

import businessLogic.BookStore;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class StartWindow extends javax.swing.JFrame {

    public StartWindow() {
        initComponents();
        
        setTitle("\ud83d\udcda Bookotá");
        setIconImage ( new ImageIcon(getClass().getResource("/Imagen/Bookota.png")).getImage());
        setLocationRelativeTo(null);
        
        ImageIcon imagen1 = new ImageIcon( getClass().getResource("/Imagen/Bookota.png"));
        Icon fondo1 =new ImageIcon ( imagen1.getImage().getScaledInstance(jLabelBookotaLogo.getWidth(), jLabelBookotaLogo.getHeight(),Image.SCALE_SMOOTH));
        jLabelBookotaLogo.setIcon(fondo1);
        this.repaint();
                    
        ImageIcon imagen2 = new ImageIcon( getClass().getResource("/Imagen/BookHome.jpg"));
        Icon fondo2 =new ImageIcon ( imagen2.getImage().getScaledInstance(jLabelBooksStartingScreen.getWidth(), jLabelBooksStartingScreen.getHeight(),Image.SCALE_SMOOTH));
        jLabelBooksStartingScreen.setIcon(fondo2);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelStartingScreenBackground = new javax.swing.JPanel();
        jLabelBooksStartingScreen = new javax.swing.JLabel();
        jPanelRightsReservedBackground = new javax.swing.JPanel();
        jLabelRightsReserved = new javax.swing.JLabel();
        jLabelBookotaLogo = new javax.swing.JLabel();
        jLabelWelcomeMessage = new javax.swing.JLabel();
        jLabelNewUserMessage = new javax.swing.JLabel();
        jLabelAlreadyUser = new javax.swing.JLabel();
        jbSignUp = new javax.swing.JButton();
        jbLogIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelStartingScreenBackground.setBackground(new java.awt.Color(40, 47, 93));

        jPanelRightsReservedBackground.setBackground(new java.awt.Color(255, 255, 255));

        jLabelRightsReserved.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabelRightsReserved.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRightsReserved.setText("© Todos los derechos reservados. 2019.");

        javax.swing.GroupLayout jPanelRightsReservedBackgroundLayout = new javax.swing.GroupLayout(jPanelRightsReservedBackground);
        jPanelRightsReservedBackground.setLayout(jPanelRightsReservedBackgroundLayout);
        jPanelRightsReservedBackgroundLayout.setHorizontalGroup(
            jPanelRightsReservedBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightsReservedBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRightsReserved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRightsReservedBackgroundLayout.setVerticalGroup(
            jPanelRightsReservedBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRightsReservedBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRightsReserved)
                .addContainerGap())
        );

        jLabelWelcomeMessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelWelcomeMessage.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcomeMessage.setText("¡ Bienvenido a Bookotá !");

        jLabelNewUserMessage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNewUserMessage.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNewUserMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewUserMessage.setText("¿Eres nuevo en Bookotá?");

        jLabelAlreadyUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelAlreadyUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAlreadyUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAlreadyUser.setText("¿Ya tienes una cuenta?");

        jbSignUp.setText("Regístrate");
        jbSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbSignUpMouseEntered(evt);
            }
        });
        jbSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSignUpActionPerformed(evt);
            }
        });

        jbLogIn.setText("Inicia sesión");
        jbLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbLogInMouseEntered(evt);
            }
        });
        jbLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStartingScreenBackgroundLayout = new javax.swing.GroupLayout(jPanelStartingScreenBackground);
        jPanelStartingScreenBackground.setLayout(jPanelStartingScreenBackgroundLayout);
        jPanelStartingScreenBackgroundLayout.setHorizontalGroup(
            jPanelStartingScreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRightsReservedBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelStartingScreenBackgroundLayout.createSequentialGroup()
                .addComponent(jLabelBooksStartingScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanelStartingScreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStartingScreenBackgroundLayout.createSequentialGroup()
                        .addGroup(jPanelStartingScreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelWelcomeMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStartingScreenBackgroundLayout.createSequentialGroup()
                                .addGroup(jPanelStartingScreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAlreadyUser, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNewUserMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStartingScreenBackgroundLayout.createSequentialGroup()
                                .addComponent(jbLogIn)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStartingScreenBackgroundLayout.createSequentialGroup()
                                .addComponent(jbSignUp)
                                .addGap(41, 41, 41)))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStartingScreenBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabelBookotaLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );
        jPanelStartingScreenBackgroundLayout.setVerticalGroup(
            jPanelStartingScreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStartingScreenBackgroundLayout.createSequentialGroup()
                .addGroup(jPanelStartingScreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBooksStartingScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelStartingScreenBackgroundLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabelBookotaLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabelWelcomeMessage)
                        .addGap(30, 30, 30)
                        .addComponent(jLabelNewUserMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSignUp)
                        .addGap(31, 31, 31)
                        .addComponent(jLabelAlreadyUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbLogIn)))
                .addGap(6, 6, 6)
                .addComponent(jPanelRightsReservedBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelStartingScreenBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelStartingScreenBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSignUpActionPerformed
        setVisible(false);
        RegisterWindow ventanaRegistro = new RegisterWindow();
        ventanaRegistro.setVisible(true);
    }//GEN-LAST:event_jbSignUpActionPerformed

    private void jbLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogInActionPerformed
        setVisible(false);
        LogInWindow ventanaInicioSesion = new LogInWindow();
        ventanaInicioSesion.setVisible(true);
    }//GEN-LAST:event_jbLogInActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        BookStore.close(rootPane);
    }//GEN-LAST:event_formWindowClosing

    private void jbSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSignUpMouseEntered
        jbSignUp.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_jbSignUpMouseEntered

    private void jbLogInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbLogInMouseEntered
        jbLogIn.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_jbLogInMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAlreadyUser;
    private javax.swing.JLabel jLabelBookotaLogo;
    private javax.swing.JLabel jLabelBooksStartingScreen;
    private javax.swing.JLabel jLabelNewUserMessage;
    private javax.swing.JLabel jLabelRightsReserved;
    private javax.swing.JLabel jLabelWelcomeMessage;
    private javax.swing.JPanel jPanelRightsReservedBackground;
    private javax.swing.JPanel jPanelStartingScreenBackground;
    private javax.swing.JButton jbLogIn;
    private javax.swing.JButton jbSignUp;
    // End of variables declaration//GEN-END:variables
}
